### ISSUE TITLE
Refactor CLI with JCommander/Args4j and Hadoop Configured/Tool interface

### ISSUE THREAD

**Issue by laserson** [opencb/hpg-bigdata#25]
This will make it easier to integrate with Hadoop job runner and also easier to deal with adding/manipulating command line options.

**Comment by imedina** [comment]
Hi, sounds interesting, could you provide one example or point out one of the problems?

**Comment by laserson** [comment]
Actually, the Quince tools are using JCommander. It can integrate nicely this way with the semantics that Hadoop expects for submitting jobs, while giving you the nice CLI args processing.

**Comment by imedina** [comment]
All Java-based OpenCB projects use JCommander as well, including HPG BigData. In module hpg-bigdata-app parameters are defined in:
https://github.com/opencb/hpg-bigdata/blob/develop/hpg-bigdata-app/src/main/java/org/opencb/hpg/bigdata/app/cli/hadoop/CliOptionsParser.java

and the main class at https://github.com/opencb/hpg-bigdata/blob/develop/hpg-bigdata-app/src/main/java/org/opencb/hpg/bigdata/app/BigDataMain.java

**Comment by laserson** [comment]
I'll close for now
