### ISSUE TITLE
Native C implementation of BAM converter

### ISSUE THREAD

**Issue by imedina** [opencb/hpg-bigdata#5]
Converting BAM files into Avro using Java implementation takes too longer. Using Avro C library could provide some speed ups.

**Comment by jtarraga** [comment]
Bam2Avro comparison: Hadoop/MapReduce (Java) vs Native C implementation

Dataset: 9M.bam (989MBytes, 9573484 alignments)

```
    $ hdfs dfs -mkdir hdfs:///native
```

**Java scenario**:
- Copy 9M.bam from local to HDFS:

```
    $ time hdfs dfs -copyFromLocal ~/datasets/9M.bam hdfs:///native
    real    0m12.663s
    user    0m5.361s
    sys 0m0.499s
```
- Convert to GA4GH Avro schema using MapReduce (one mapper one reduce):

```
    time ./build/bin/hpg-bigdata.sh convert -c bam2avro -i hdfs:///native/9M.bam -o hdfs:///native/9M.bam.deflafe.avro -x deflate
    real    15m19.426s
    user    13m35.251s
    sys 0m22.525s
```
- Total time: 0m12.663s + 15m19.426s = **15m 32.089s**

**Native C scenario**:
- Convert to GA4GH Avro schema using native C implementation:

```
    $ time ./build/bin/hpg-bigdata-local.sh convert -c bam2avro -i ~/datasets/9M.bam -o ~/datasets/9M.bam.native.deflate.avro -x deflate
    real    5m55.356s
    user    5m34.571s
    sys 0m2.715s
```
- Copy 9M.bam from local to HDFS:

```
    $ time hdfs dfs -copyFromLocal ~/datasets/9M.bam.native.deflate.avro hdfs:///native/9M.bam.native.deflate.avro
    real    0m16.739s
    user    0m6.422s
    sys 0m0.801s

```
- Total time: 5m55.356s + 0m16.739s = **6m 12.095s**
